language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo fmt -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test pass
  - cargo test --doc
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
